apiVersion: cloud.oceanbase.com/v1
kind: OBCluster
metadata:
  name: ob-test
spec:
  version: v3.1.2-10000392021123010
  clusterID: 1
  topology:
    - cluster: cn
      zone:
        - name: zone1
          region: region1
          nodeSelector:
            topology.kubernetes.io/zone: zone1
          replicas: 1
        - name: zone2
          region: region1
          nodeSelector:
            topology.kubernetes.io/zone: zone2
          replicas: 1
        - name: zone3
          region: region1
          nodeSelector:
            topology.kubernetes.io/zone: zone3
          replicas: 1
  resources:
    cpu: 2
    memory: 10Gi
    storage:
      - name: data-file
        storageClassName: "local-path"
        size: 50Gi
      - name: data-log
        storageClassName: "local-path"
        size: 50Gi
      - name: log
        storageClassName: "local-path"
        size: 30Gi